/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['controllers/passports.js']) {
  _$jscoverage['controllers/passports.js'] = [];
  _$jscoverage['controllers/passports.js'][1] = 0;
  _$jscoverage['controllers/passports.js'][2] = 0;
  _$jscoverage['controllers/passports.js'][4] = 0;
  _$jscoverage['controllers/passports.js'][5] = 0;
  _$jscoverage['controllers/passports.js'][8] = 0;
  _$jscoverage['controllers/passports.js'][9] = 0;
  _$jscoverage['controllers/passports.js'][12] = 0;
  _$jscoverage['controllers/passports.js'][14] = 0;
  _$jscoverage['controllers/passports.js'][17] = 0;
  _$jscoverage['controllers/passports.js'][18] = 0;
  _$jscoverage['controllers/passports.js'][21] = 0;
  _$jscoverage['controllers/passports.js'][22] = 0;
  _$jscoverage['controllers/passports.js'][25] = 0;
  _$jscoverage['controllers/passports.js'][27] = 0;
  _$jscoverage['controllers/passports.js'][30] = 0;
  _$jscoverage['controllers/passports.js'][31] = 0;
  _$jscoverage['controllers/passports.js'][36] = 0;
}
_$jscoverage['controllers/passports.js'][1]++;
var Passports = (function () {
  _$jscoverage['controllers/passports.js'][2]++;
  this.respondsWith = ["html", "json", "xml", "js", "txt"];
  _$jscoverage['controllers/passports.js'][4]++;
  this.index = (function (req, resp, params) {
  _$jscoverage['controllers/passports.js'][5]++;
  this.respond({params: params});
});
  _$jscoverage['controllers/passports.js'][8]++;
  this.add = (function (req, resp, params) {
  _$jscoverage['controllers/passports.js'][9]++;
  this.respond({params: params});
});
  _$jscoverage['controllers/passports.js'][12]++;
  this.create = (function (req, resp, params) {
  _$jscoverage['controllers/passports.js'][14]++;
  this.redirect({controller: this.name});
});
  _$jscoverage['controllers/passports.js'][17]++;
  this.show = (function (req, resp, params) {
  _$jscoverage['controllers/passports.js'][18]++;
  this.respond({params: params});
});
  _$jscoverage['controllers/passports.js'][21]++;
  this.edit = (function (req, resp, params) {
  _$jscoverage['controllers/passports.js'][22]++;
  this.respond({params: params});
});
  _$jscoverage['controllers/passports.js'][25]++;
  this.update = (function (req, resp, params) {
  _$jscoverage['controllers/passports.js'][27]++;
  this.redirect({controller: this.name, id: params.id});
});
  _$jscoverage['controllers/passports.js'][30]++;
  this.destroy = (function (req, resp, params) {
  _$jscoverage['controllers/passports.js'][31]++;
  this.respond({params: params});
});
});
_$jscoverage['controllers/passports.js'][36]++;
exports.Passports = Passports;
_$jscoverage['controllers/passports.js'].source = ["var Passports = function () {","  this.respondsWith = ['html', 'json', 'xml', 'js', 'txt'];","","  this.index = function (req, resp, params) {","    this.respond({params: params});","  };","","  this.add = function (req, resp, params) {","    this.respond({params: params});","  };","","  this.create = function (req, resp, params) {","    // Save the resource, then display index page","    this.redirect({controller: this.name});","  };","","  this.show = function (req, resp, params) {","    this.respond({params: params});","  };","","  this.edit = function (req, resp, params) {","    this.respond({params: params});","  };","","  this.update = function (req, resp, params) {","    // Save the resource, then display the item page","    this.redirect({controller: this.name, id: params.id});","  };","","  this.destroy = function (req, resp, params) {","    this.respond({params: params});","  };","","};","","exports.Passports = Passports;",""];
