/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['models/passport.js']) {
  _$jscoverage['models/passport.js'] = [];
  _$jscoverage['models/passport.js'][1] = 0;
  _$jscoverage['models/passport.js'][2] = 0;
  _$jscoverage['models/passport.js'][3] = 0;
  _$jscoverage['models/passport.js'][5] = 0;
  _$jscoverage['models/passport.js'][8] = 0;
}
_$jscoverage['models/passport.js'][1]++;
var Passport = (function () {
  _$jscoverage['models/passport.js'][2]++;
  this.property("authType", "string");
  _$jscoverage['models/passport.js'][3]++;
  this.property("key", "string");
  _$jscoverage['models/passport.js'][5]++;
  this.belongsTo("User");
});
_$jscoverage['models/passport.js'][8]++;
Passport = geddy.model.register("Passport", Passport);
_$jscoverage['models/passport.js'].source = ["var Passport = function () {","  this.property('authType', 'string');","  this.property('key', 'string');","","  this.belongsTo('User');","};","","Passport = geddy.model.register('Passport', Passport);",""];
